### ISSUE TITLE
Visual Representation of Feature Relations

### ISSUE THREAD

**Issue by MisterGC** [ndsev/erdblick#9] opened 2023-06-09 14:54 UTC
The system should support the visualization of relationships between different map features. For instance, if a traffic light is related to a specific stretch of lane, selecting the traffic light in the map viewer should directly highlight or otherwise visually indicate the associated lane stretch.

The relationships should be displayed in a way that is clear but unobtrusive, so as not to interfere with the overall map view. This could involve using distinctive colors, lines, or other visual indicators to represent the relationships.

Users should have the ability to activate or deactivate this relationship visualization according to their needs. When the visualization is deactivated, the map should return to its standard view, without the relationship indicators.

**Comment by josephbirkner** [comment] 2024-03-12 07:11
Duplicate of #75

**Closed by josephbirkner** 2024-03-12 07:11 UTC
Labels: EPIC :sparkler:, Styling :sparkles:, Unrefined :eyes:
